FROM golang:1.16.2-alpine as builder
WORKDIR /app
ENV GO111MODULE=on
COPY . /app
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o geodns-go ./cmd/geodns/geodns.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/geodns-go /app/geodns-go
CMD ["/app/geodns-go"]
